server {
    listen 80;
    server_name _;

    # Frontend (statische Dateien)
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_intercept_errors on;
    }

    # Backend API
    location /api {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;          # WICHTIG: nginx nutzt default HTTP/1.0 fuer proxy_pass
        client_max_body_size 50M;        # WICHTIG: Default ist 1MB, größere Uploads sonst blockiert
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Websocket
    location /ws {
        proxy_pass http://backend:8080/ws;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

     location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
     }
}