server {
    listen 80;
    server_name _;

    # LetsEncrypt ACME Challenge (fuer spaeter)
        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
        }

    # Alles andere auf HTTPS weiterleiten
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/private/key.pem;

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_ciphers               HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;


    # Frontend (statische Dateien)
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_intercept_errors on;
    }

    # Backend API
    location /api {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        client_max_body_size 50M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Websocket
    location /ws {
        proxy_pass http://backend:8080/ws;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

     location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
     }
}