spring.application.name=schroedingerschat
server.port=8080
spring.jpa.open-in-view=false
jwt.token.prefix=Bearer
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# MinIO Konfiguration
minio.endpoint=http://localhost:9000
minio.access.name=schroedingersFiles-Admin
minio.access.secret=87654321
minio.bucket.name=schroedingersFiles