
spring.application.name=schroedingerschat
server.port=8080

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false


#spring.application.name=backend
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2

# spring.datasource.url=jdbc:postgresql://db:5432/postgres
# spring.datasource.username=admin
# spring.datasource.password=1234
# spring.datasource.driverClassName=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.token.secret = mOSHcH0eNFFyPVnsDARM33Wou00jANyTtkMaD3mZWFHAy6wcMVJKwsfu6sRg3LSIHgjhZfvxMih13bcPL22yWY
jwt.token.prefix = Bearer



# OLD FILE:

#spring.application.name=backend
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#
## spring.datasource.url=jdbc:postgresql://db:5432/postgres
## spring.datasource.username=admin
## spring.datasource.password=1234
## spring.datasource.driverClassName=org.postgresql.Driver
## spring.jpa.hibernate.ddl-auto=update
## spring.jpa.show-sql=true
## spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
##JWT
#jwt.token.secret = mOSHcH0eNFFyPVnsDARM33Wou00jANyTtkMaD3mZWFHAy6wcMVJKwsfu6sRg3LSIHgjhZfvxMih13bcPL22yWY
#jwt.token.prefix = Bearer
#
##Superadmin for testing purposes
#spring.profiles.active=dev