# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/schroedingerschat
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SuperAdmin Credentials (aus Environment Variablen)
superadmin.email=${SUPERADMIN_EMAIL}
superadmin.password=${SUPERADMIN_PASSWORD}

jwt.token.secret=${JWT_SECRET}

# MinIO Konfiguration
minio.endpoint=http://minio:9000
minio.access.name=${MINIO_ROOT_USER}
minio.access.secret=${MINIO_ROOT_PASSWORD}
minio.bucket.name=schroedingers-files

encryption.master-key=${ENCRYPTION_MASTER_KEY}